# SITE CONFIGURATION
title: Paroparo # your site title
author: iltruma # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sass:
    sass_dir: _sass
    style: compressed

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blog', link: '/blog'}
  - {name: 'Feed', link: '/feed'}
  - {name: 'Chi Siamo', link: '/chi-siamo'}
  - {name: 'Contatti', link: '/contatti'}

email: your-email@domain.com # email for form submission

twitter_username: iltruma # replace with your_twitter_username or comment to remove link from footer
github_username:  iltruma # replace with your_github_username or comment to remove link from footer
instagram_username: iltruma # replace with your_instagram_username or comment to remove link from footer

# BUILD SETTINGS
markdown: kramdown
#highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-spaceship
  #- jekyll-paginate
  #- jekyll-feed
  #- jekyll-sitemap
  - jekyll-watch
  - jekyll-get-json

jekyll_get_json:
  - data: feed
    json: 'https://profilepageimages.usecue.com/images/casini.cosimo/images.json'