# SITE CONFIGURATION
title: Paroparo # your site title
author: iltruma # You :P
description: "Paroparo description"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paroparo.it" # the base hostname & protocol for your site, e.g. http://example.com

#sass:
#    sass_dir: _sass
#    style: compressed

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blog', link: '/blog'}
  - {name: 'Feed', link: '/feed'}
  - {name: 'Chi Siamo', link: '/chi-siamo'}
  - {name: 'Contatti', link: '/contatti'}

#SEO
#tagline: "" # A short description title | tagline header
#facebook:
#  app_id: 1234
#  publisher: 1234
#  admins: 1234
#logo: 
#social:
#  name: Paroparo
#  links:
#    - https://instagram.com/paroparo
#google_site_verification: 
email: info@paroparo.it
email_1: niccolo@paroparo.it
email_2: cosimo@paroparo.it
address: "Foresta di Figline Valdarno"
city: "Firenze, Italia"
locale: it_IT

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - assets

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

#PAGINATION
pagination:
  enabled: true
  per_page: 10
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

jekyll_get_json:
  - data: feed
    json: 'https://profilepageimages.usecue.com/images/casini.cosimo/images.json'

plugins:
  - jekyll-spaceship
  - jekyll-watch
  - jekyll-get-json
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2