# SITE CONFIGURATION
title: Paroparo 
author: iltruma
description: "Modern problems require modern solutions. It's a Paroparo Philosophy."
baseurl: ""
url: "https://www.paroparo.it"
email: info@paroparo.it
email_1: niccolo@paroparo.it
email_2: cosimo@paroparo.it
address: "Foresta di Figline Valdarno"
city: "Firenze, Italia"
locale: it_IT
timezone: Europe/Rome
environment: prod
#version: "1.0"

# NAVIGATION
navigation:
  - {name: 'Feed', link: '/feed'}
  - {name: 'Chi Siamo', link: '/chi-siamo'}
  - {name: 'Contatti', link: '/contatti'}

#THEME 
colors:
  - primary: "#186e64"
  - primary-2: "#FF6933"
  - primary-3: "#2DE0CB"
  - primary-4: "#6600FF"
  - primary-dark: "#021C19"
  - primary-2-dark: "#242331"
  - primary-night: "#121212"

#SEO
#google_site_verification: 
logo: "/assets/img/favicons/pp_logo.svg"
social:
  links:
    - github: "https://github.com/iltruma/paroparo"
    - instagram: "https://www.instagram.com/paroparo.it"
defaults:
  - scope:
      path: ""
    values:
      image: assets/img/gitpreview.webp

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
  - node_modules
  - script
  - package*.json
  - Gemfile*
  - npm-debug.log
  - gulpfile.js
  - Dockerfile*
  - paroparo.gemspec
keep_files:
  - assets
permalink: /:title/
collections:
  pages:
    output: true
    permalink: /:title/


#PAGINATION
pagination:
  enabled: true
  per_page: 10
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

jekyll_get_json:
  - data: feed
    json: 'https://profilepageimages.usecue.com/images/paroparo.it/images.json'

plugins:
  - jekyll-spaceship
  - jekyll-watch
  - jekyll-get-json
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-email-protect

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []