# SITE CONFIGURATION
title: Paroparo # your site title
author: iltruma # You :P
description: "Paroparo description"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
address: "Foresta di Figline Valdarno"
city: "Firenze, Italia"

sass:
    sass_dir: _sass
    style: compressed

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blog', link: '/blog'}
  - {name: 'Feed', link: '/feed'}
  - {name: 'Chi Siamo', link: '/chi-siamo'}
  - {name: 'Contatti', link: '/contatti'}

email: info@paroparo.it
email_1: niccolo@paroparo.it
email_2: cosimo@paroparo.it

# BUILD SETTINGS
markdown: kramdown
#highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-spaceship
  #- jekyll-paginate
  #- jekyll-feed
  #- jekyll-sitemap
  - jekyll-watch
  - jekyll-get-json
  - jekyll-minifier

jekyll_get_json:
  - data: feed
    json: 'https://profilepageimages.usecue.com/images/casini.cosimo/images.json'