name: Metrics Generator

on:
  workflow_dispatch: #Manually Schedule

jobs:
  gh_metrics_generator:
      runs-on: ubuntu-latest
      steps: 
        - name: ⚡ Cache Github Metrics
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-metrics-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-metrics-
              
        - name: 📊 Github Metrics Generator
          if: ${{ success() || failure() }}
          uses: lowlighter/metrics@latest
          with:
            config_timezone: Europe/Rome
            token: ${{ secrets.GITH_TOKEN }}
            template: repository
            filename: assets/img/metrics.svg
            user: iltruma
            repo: paroparo
            base: header
            config_display: large
            plugin_introduction: yes
            plugin_introduction_title: no # Hide section title
            plugin_lines: yes
            plugin_followup: yes
            plugin_activity: yes
            plugin_activity_days: 14
            plugin_activity_filter: all
            plugin_activity_limit: 5
            plugin_languages: yes
            plugin_languages_colors: github
            plugin_languages_limit: 8
            plugin_languages_sections: most-used
