name: Metrics Generator

on:
  schedule:
    - cron:  '0 0 * * *' #Every day schedule
  workflow_dispatch:
  
jobs:
  metrics_generator:
    runs-on: ubuntu-latest
    steps: 
      - name: Metrics Generator
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITH_TOKEN }}
          template: repository
          filename: metrics.svg
          user: iltruma
          repo: paroparo
          base: header
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
  
  
